sudo: required
services:
  - docker

before_install:
  - docker build -t bhades/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bhades/react-test npm run test -- --coverage

after_success:
  - docker build -t bhades/multi-client ./client
  - docker build -t bhades/multi-nginx ./nginx
  - docker build -t bhades/multi-server ./server
  - docker build -t bhades/multi-worker ./worker

  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images
  - docker push bhades/multi-client
  - docker push bhades/multi-nginx
  - docker push bhades/multi-server
  - docker push bhades/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-668009757711
  bucket_patch: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
